### ISSUE TITLE
Missing product with ID 87

### ISSUE THREAD

**Issue by liko9** [LIFX/products#11]
Very similar to https://github.com/LIFX/products/issues/9, I just purchased a bulb identifying itself as ID 87 (https://smile.amazon.com/dp/B0865TRD5L/ref=cm_sw_r_tw_dp_6alKFb3JB7FJM?_x_encoding=UTF8&psc=1) but I didn't see that in the JSON either...?

**Comment by liko9** [comment]
No idea how I overlooked it...forgive me, it's there.

**Comment by delfick** [comment]
:)
