### ISSUE TITLE
Upgrades info wrong for pid 50?

### ISSUE THREAD

**Issue by georgefst** [LIFX/products#15]
My "LIFX Mini White to Warm" reports itself (through the official Android app or my Haskell Lan API library) as being on the 3.60 firmware, with the app suggesting that this is the latest version. However, `products.json` lists upgrades for 3.70, in particular the upper temperature range being expanded. My bulb does show visible differences in the 6500-9000K range, which supposedly is only possible with 3.70+. And thus, the app makes these temperatures inaccessible.

**Comment by dntj** [comment]
3.70 firmware is currently in alpha.  We hope to release it soon to make the expanded temperature range accessible.

**Comment by georgefst** [comment]
OK, great.

(Although in that case, I don't really understand how my bulb running 3.60 is already able to access the expanded range...)
