### ISSUE TITLE
New LIFX products

### ISSUE THREAD

**Issue by Thomas-Vos** [LIFX/products#16]
One of my users reported to me a LIFX light with product identifier `lifx_z3` reported by the HTTP API.

My LIFX Z lightstrip has `lifx_z2` as identifier.

I am not sure what the ids are for this light (was not reported by the user). Could you check if the products.json still up to date?

**Comment by Thomas-Vos** [comment]
@dntj maybe you can help me out?

**Comment by paulwrussell** [comment]
@Thomas-Vos thanks for the feedback. See https://github.com/LIFX/products/pull/17

**Comment by Thomas-Vos** [comment]
Great, thanks for adding them to the list!
