### ISSUE TITLE
LIFX A19 US has multizone enabled by mistake

### ISSUE THREAD

**Issue by Djelibeybi** [LIFX/products#31]
This was reported via the Home Assistant issue tracker. A user with a LIFX A19 US bulb (PID 163) couldn't get their bulb to work because `aiolifx` was sending packets only supported by multizone devices. Turns out the `products.json` defines this bulb as multizone capable: https://github.com/LIFX/products/blob/master/products.json#L1740-L1756

Could this please be fixed?

**Comment by alessio-palumbo** [comment]
Thanks for reporting this, @Djelibeybi. It has now been fixed.
