### ISSUE TITLE
Please update with the product ID of the new LIFX Clean device

### ISSUE THREAD

**Issue by wwsean08** [LIFX/products#7]
Hello,

Please update this json document with the data for the new LIFX Clean device and it's capabilities.

Sean

**Comment by delfick** [comment]
Hello,

The LIFX Clean is still in development. We'll be rolling out public information about the product as that progresses.

**Comment by frawau** [comment]
I'll wait then

**Comment by wwsean08** [comment]
Sounds good, based on the announcement I thought development might be complete :)

**Comment by delfick** [comment]
the LIFX clean has now been added :)
