### ISSUE TITLE
Add HTTP API product identifiers to products.json

### ISSUE THREAD

**Issue by Thomas-Vos** [LIFX/products#8]
It would be great if you could add the product identifier (like `lifx_color_a19`) that is returned using the HTTP API to the products.json file. We would like to use this for matching all of the LIFX lights to icons in our app. Currently there is not a list anywhere which contains all of the product identifiers of the HTTP API.

An alternative solution would be to add the vendor and product id to the HTTP API so we can use products.json.

**Comment by delfick** [comment]
Hello,

We decided not to add the identifier strings to the public registry. But adding the product id to the /v1/lights output makes a lot of sense and turns out to be a very simple change. So I was able to slip that in today and now it's live

```
> curl https://api.lifx.co/v1/lights -H"Authorization: Bearer $PROD_API_TOKEN" | jq \
    '.[] | .id + ": " + .label + " > " + (.product.product_id | tostring)' --raw-output
```

Thanks for the suggestion!
